import type { LucideIcon } from "lucide-react";
import {
  Bird,
  Bike,
  Binoculars,
  BookOpen,
  BookText,
  Brain,
  BusFront,
  Camera,
  CameraOff,
  Candy,
  Cat,
  ChefHat,
  Code2,
  Coffee,
  Compass,
  CookingPot,
  Dog,
  Dribbble,
  Dumbbell,
  Fish,
  Film,
  Gamepad2,
  Globe,
  Goal,
  Guitar,
  Headphones,
  Joystick,
  Languages,
  Laptop,
  Map,
  Martini,
  Mic,
  Mountain,
  Music,
  Palette,
  PenLine,
  PenTool,
  Piano,
  Pizza,
  Plane,
  Podcast,
  Puzzle,
  Rocket,
  Scissors,
  Shirt,
  Smile,
  Swords,
  Tent,
  Theater,
  Trees,
  Trophy,
  Volleyball,
  Waves,
} from "lucide-react";

export interface HobbyIconOption {
  value: string;
  label: string;
  icon: LucideIcon;
}

export const HOBBY_ICON_OPTIONS: HobbyIconOption[] = [
  { value: "guitar", label: "Guitar", icon: Guitar },
  { value: "gamepad-2", label: "Gaming", icon: Gamepad2 },
  { value: "camera-off", label: "Filmmaking", icon: CameraOff },
  { value: "camera", label: "Photography", icon: Camera },
  { value: "dumbbell", label: "Fitness", icon: Dumbbell },
  { value: "binoculars", label: "Birdwatching", icon: Binoculars },
  { value: "bike", label: "Cycling", icon: Bike },
  { value: "book-open", label: "Reading", icon: BookOpen },
  { value: "book-text", label: "Journaling", icon: BookText },
  { value: "music", label: "Music", icon: Music },
  { value: "mic", label: "Singing", icon: Mic },
  { value: "podcast", label: "Podcasting", icon: Podcast },
  { value: "piano", label: "Piano", icon: Piano },
  { value: "plane", label: "Travel", icon: Plane },
  { value: "globe", label: "Geography", icon: Globe },
  { value: "compass", label: "Orienteering", icon: Compass },
  { value: "map", label: "Map Exploration", icon: Map },
  { value: "tent", label: "Camping", icon: Tent },
  { value: "bird", label: "Birds", icon: Bird },
  { value: "fish", label: "Fishing", icon: Fish },
  { value: "cooking-pot", label: "Cooking", icon: CookingPot },
  { value: "chef-hat", label: "Baking", icon: ChefHat },
  { value: "coffee", label: "Coffee", icon: Coffee },
  { value: "martini", label: "Mixology", icon: Martini },
  { value: "pizza", label: "Food", icon: Pizza },
  { value: "candy", label: "Desserts", icon: Candy },
  { value: "trees", label: "Nature", icon: Trees },
  { value: "code-2", label: "Coding", icon: Code2 },
  { value: "brain", label: "Learning", icon: Brain },
  { value: "languages", label: "Languages", icon: Languages },
  { value: "pen-tool", label: "Design", icon: PenTool },
  { value: "mountain", label: "Hiking", icon: Mountain },
  { value: "palette", label: "Painting", icon: Palette },
  { value: "film", label: "Movies", icon: Film },
  { value: "theater", label: "Theater", icon: Theater },
  { value: "headphones", label: "Podcasts", icon: Headphones },
  { value: "laptop", label: "Tech", icon: Laptop },
  { value: "pen-line", label: "Writing", icon: PenLine },
  { value: "puzzle", label: "Puzzles", icon: Puzzle },
  { value: "rocket", label: "Space", icon: Rocket },
  { value: "scissors", label: "Crafts", icon: Scissors },
  { value: "shirt", label: "Fashion", icon: Shirt },
  { value: "trophy", label: "Sports", icon: Trophy },
  { value: "goal", label: "Soccer", icon: Goal },
  { value: "basketball", label: "Basketball", icon: Dribbble },
  { value: "volleyball", label: "Volleyball", icon: Volleyball },
  { value: "swords", label: "Fencing", icon: Swords },
  { value: "waves", label: "Surfing", icon: Waves },
  { value: "joystick", label: "Arcade", icon: Joystick },
  { value: "bus-front", label: "Road Trips", icon: BusFront },
  { value: "cat", label: "Cats", icon: Cat },
  { value: "dog", label: "Dogs", icon: Dog },
];

const ICON_BY_NAME = HOBBY_ICON_OPTIONS.reduce<Record<string, LucideIcon>>(
  (acc, option) => {
    acc[option.value] = option.icon;
    return acc;
  },
  {}
);

export function getHobbyIcon(iconName: string | null | undefined): LucideIcon {
  if (!iconName) return Smile;
  return ICON_BY_NAME[iconName] ?? Smile;
}
